name: Export Conversion Rules
on:
  push:
    branches:
      - main
      - dev
      - issue/**
      - add-utils-compile-status
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Export Conversion Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy converter_base to current directory Linux, MacOS
        run: |
          cp -r focus_converter_base/* ./

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry lock
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Create conversion rule export directory
        run: |
          mkdir -p conversion_rules_export/{markdown,csv}
      - name: Generate rule export
        run: |
          poetry run focus-export-conversion-rules  --output-dir conversion_rules_export/markdown --output-format markdown
          poetry run focus-export-conversion-rules  --output-dir conversion_rules_export/csv --output-format csv
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add : 'conversion_rules_export'
          author_name: FinOps Converter Bot
          author_email: finops-converter-bot@finops.org
          commit: --signoff
